using System;
using System.IO;
using System.Linq;

using NUnit.Framework;

using Org.BouncyCastle.Utilities.Encoders;

namespace Org.BouncyCastle.Bcpg.OpenPgp.Tests
{
    /// <summary>
    /// Version 6 certificates, RFC 9580.
    /// </summary>
    /// <remarks>
    /// Every expected value here comes from outside this codebase: the RFC
    /// itself for the first certificate, and Sequoia (sq 1.3.1) for the rest.
    /// </remarks>
    [TestFixture]
    public class PgpV6CertificateTest
    {
        /// <summary>RFC 9580 appendix A.3, the sample version 6 certificate.</summary>
        private const string RfcSampleCertificate =
            "-----BEGIN PGP PUBLIC KEY BLOCK-----\n" +
            "\n" +
            "xioGY4d/4xsAAAAg+U2nu0jWCmHlZ3BqZYfQMxmZu52JGggkLq2EVD34laPCsQYf\n" +
            "GwoAAABCBYJjh3/jAwsJBwUVCg4IDAIWAAKbAwIeCSIhBssYbE8GCaaX5NUt+mxy\n" +
            "KwwfHifBilZwj2Ul7Ce62azJBScJAgcCAAAAAK0oIBA+LX0ifsDm185Ecds2v8lw\n" +
            "gyU2kCcUmKfvBXbAf6rhRYWzuQOwEn7E/aLwIwRaLsdry0+VcallHhSu4RN6HWaE\n" +
            "QsiPlR4zxP/TP7mhfVEe7XWPxtnMUMtf15OyA51YBM4qBmOHf+MZAAAAIIaTJINn\n" +
            "+eUBXbki+PSAld2nhJh/LVmFsS+60WyvXkQ1wpsGGBsKAAAALAWCY4d/4wKbDCIh\n" +
            "BssYbE8GCaaX5NUt+mxyKwwfHifBilZwj2Ul7Ce62azJAAAAAAQBIKbpGG2dWTX8\n" +
            "j+VjFM21J0hqWlEg+bdiojWnKfA5AQpWUWtnNwDEM0g12vYxoWM8Y81W+bHBw805\n" +
            "I8kWVkXU6vFOi+HWvv/ira7ofJu16NnoUkhclkUrk0mXubZvyl4GBg==\n" +
            "-----END PGP PUBLIC KEY BLOCK-----\n";

        /// <summary>RFC 9580 appendix A.3 states this fingerprint.</summary>
        private const string RfcSampleFingerprint =
            "CB186C4F0609A697E4D52DFA6C722B0C1F1E27C18A56708F6525EC27BAD9ACC9";

        /// <summary>
        /// Generated by Sequoia: sq key generate --profile rfc9580 --expiration 2y.
        /// An independent implementation, which is what makes these assertions
        /// worth anything.
        /// </summary>
        private const string SequoiaCertificate =
            "-----BEGIN PGP PUBLIC KEY BLOCK-----\n" +
            "\n" +
            "xioGan1S4hsAAAAg1TXjLdvPZXc46m/kGLQUi1jXH77Tev+cJBsJBwvS8/vCrAYf\n" +
            "GwoAAAA9BYJqfVLiBYkDwwp+AwsJBwMVCggCmwECHgkiIQaU8M4Ab5nGMCrc2mst\n" +
            "OXx+o5L577Djkhpp+ap3JV8GEwAAAABe3yAC5bpIzZYIsv8qV5cp3onROgaTZNYD\n" +
            "+lLCfhCNYxzJbQDiP0rsVp4Fw6cRu957sL4ju3AozKCs+0R0zqJFip/q4XVm/Euj\n" +
            "Cw9+iDLooMZHgRa03VCbHt8ZD93MIY7tAQHNEzx2NmV4cEBleGFtcGxlLmNvbT7C\n" +
            "rwYTGwoAAABABYJqfVLiBYkDwwp+AwsJBwMVCggCmQECmwECHgkiIQaU8M4Ab5nG\n" +
            "MCrc2mstOXx+o5L577Djkhpp+ap3JV8GEwAAAAA8tyB5eB90xSJ2nj8TgjgBgS/v\n" +
            "bRlBhi+qkHhG9hlvioaSDLXw6WtcbRnTLbRBSjIO/woHfsZgkvUIqisZbhHbrTKQ\n" +
            "EMVNSJ2GBlmxM3Z0p6wRni7llBFFAM5t72HKH4q2RADOKgZqfVLiGQAAACA+FpUy\n" +
            "rBq56ICFbNoPo7Z8u1/Aaobva+b4mo3jQx/uNcKhBhgbCgAAADIFgmp9UuIFiQPD\n" +
            "Cn4CmwwiIQaU8M4Ab5nGMCrc2mstOXx+o5L577Djkhpp+ap3JV8GEwAAAACIryC5\n" +
            "RWKe+mrsi4cjs21njT+XjxG3oTVrIoM558EyFKVHKe5/LiJla6x8j611n+rPFhuk\n" +
            "PuhZ6ln3sdA7IpcsyhYX9uGVRtguFi2xsohhWNDeYDx4Yt/A01L4XOS8Q+8TeQ3O\n" +
            "KgZqfVLiGwAAACAQA5ihAqmctMyoJuHiKWBeIFb4c9nOv3DuGr00WdTwQMLAewYY\n" +
            "GwoAAADMBYJqfVLiBYkDwwp+ApsCmaAGGRsKAAAAKQWCan1S4iIhBo8KR2VgAYyA\n" +
            "OEcaBeWWilmDcDlZUMYiMsCUSovFuKGHAAAAAM21IJ6GFcNQ22pkqH3mlXvXvl7p\n" +
            "s2LCKPu4JCHHx+VIj9b2nabkA6ylfN8bvXyOhypnZlU3TqOa+yoYOJZbHQzSlzE5\n" +
            "UKhS4fiLiFtortUtdQA1hQHOIjrKcN4syHTxFZinAiIhBpTwzgBvmcYwKtzaay05\n" +
            "fH6jkvnvsOOSGmn5qnclXwYTAAAAAAADIJ4YXLZW4LWiiYZl44WiJIB3duKp2Z3M\n" +
            "EvgpfD5pTY668fo0RI+MW8ByKV4lYLr3TizA6VDvbA8Fyx3OBxhxexYSNhc92WmF\n" +
            "FeIcZvH8GAcoMhS/vha1ka0ST0kHOnfzC84qBmp9UuIbAAAAIGWWDAJ0pqQ6wWZ8\n" +
            "wpXHBEpJ45oJdNuwrFwwIZFrv8FNwsB7BhgbCgAAAMwFgmp9UuIFiQPDCn4CmyCZ\n" +
            "oAYZGwoAAAApBYJqfVLiIiEG6hNFwcTUWKBE/iXqes3SgY2FpADJi9ZFzuNeOaJM\n" +
            "1QkAAAAAgLwgsIQLgSA1OcyDx4XizHdcDDho9OsD3xHHl56gb9P6Lh0rW9e2dBZ+\n" +
            "QmS26zS8kHegrEn95V4coh4refQYHKBvGsRkBBRBqapxpT0Xbloa325S0SH06YEK\n" +
            "yiTrbOqnjZ4JIiEGlPDOAG+ZxjAq3NprLTl8fqOS+e+w45IaafmqdyVfBhMAAAAA\n" +
            "COcgFCdgecmUuL4A+775xK878tqNu6ZLavydFW57bHT8h4e9IxFjdMbs4fjUI5RR\n" +
            "/ySqRIpxD7XTkEx1Oy3AVp6dxxMEcv1PNjFlgZ8etaGVIS8jRxlZp7VnRWG/kO1S\n" +
            "fyoB\n" +
            "=wNpt\n" +
            "-----END PGP PUBLIC KEY BLOCK-----\n";

        /// <summary>Reported by sq inspect for <see cref="SequoiaCertificate"/>.</summary>
        private const string SequoiaFingerprint =
            "94F0CE006F99C6302ADCDA6B2D397C7EA392F9EFB0E3921A69F9AA77255F0613";

        private const string SequoiaSubkeyFingerprint =
            "D653CA2D9FDE903AF0306276340DC54D0AFA5038DFD84602254E198617BC90E9";

        [Test]
        public void RfcSampleCertificateFingerprint()
        {
            PgpPublicKey key = ReadCertificate(RfcSampleCertificate);

            Assert.AreEqual(PublicKeyPacket.Version6, key.Version);
            Assert.AreEqual(RfcSampleFingerprint, Hex.ToHexString(key.GetFingerprint()).ToUpperInvariant());
            Assert.AreEqual(PublicKeyAlgorithmTag.Ed25519, key.Algorithm);

            // RFC 9580 appendix A.3.1 annotates the creation time.
            Assert.AreEqual(new DateTime(2022, 11, 30, 16, 8, 3, DateTimeKind.Utc), key.CreationTime);
        }

        [Test]
        public void RfcSampleCertificateDirectKeySignatureVerifies()
        {
            // The whole point of the exercise: RFC 9580 5.2.3.10 requires a
            // valid Direct Key signature before a version 6 key is used, and
            // verifying it means reproducing the salted hash of 5.2.4.
            PgpPublicKey key = ReadCertificate(RfcSampleCertificate);

            PgpSignature directKey = GetSignatureOfType(key, PgpSignature.DirectKey);
            Assert.NotNull(directKey);
            Assert.AreEqual(SignaturePacket.Version6, directKey.Version);

            directKey.InitVerify(key);
            Assert.IsTrue(directKey.VerifyCertification(key));
        }

        [Test]
        public void SequoiaCertificateMatchesWhatSequoiaReports()
        {
            PgpPublicKey key = ReadCertificate(SequoiaCertificate);

            Assert.AreEqual(SequoiaFingerprint, Hex.ToHexString(key.GetFingerprint()).ToUpperInvariant());

            // sq inspect: "Expiration time: 2028-08-12 16:52:48 UTC".
            long validSeconds = key.GetValidSeconds();
            Assert.AreNotEqual(0L, validSeconds, "the expiry is carried by the Direct Key signature");
            Assert.AreEqual(new DateTime(2028, 8, 12, 16, 52, 48, DateTimeKind.Utc),
                key.CreationTime.AddSeconds(validSeconds));
        }

        [Test]
        public void SequoiaCertificateSubkeys()
        {
            PgpPublicKeyRing ring = ReadRing(SequoiaCertificate);
            PgpPublicKey[] keys = ring.GetPublicKeys().ToArray();

            Assert.AreEqual(4, keys.Length);
            Assert.AreEqual(PublicKeyAlgorithmTag.X25519, keys[1].Algorithm);
            Assert.AreEqual(PublicKeyAlgorithmTag.Ed25519, keys[2].Algorithm);
            Assert.AreEqual(PublicKeyAlgorithmTag.Ed25519, keys[3].Algorithm);

            Assert.AreEqual(SequoiaSubkeyFingerprint, Hex.ToHexString(keys[1].GetFingerprint()).ToUpperInvariant());

            foreach (PgpPublicKey subkey in keys.Skip(1))
            {
                Assert.AreEqual(PublicKeyPacket.Version6, subkey.Version);

                // A version 6 fingerprint is a SHA2-256.
                Assert.AreEqual(32, subkey.GetFingerprint().Length);
            }
        }

        [Test]
        public void KeyIdIsTheLeadingOctetsOfTheFingerprint()
        {
            // RFC 9580 5.5.4.3, and the reason a version 6 self-signature is
            // recognised as one: version 4 takes the trailing eight octets.
            PgpPublicKey key = ReadCertificate(SequoiaCertificate);

            byte[] fingerprint = key.GetFingerprint();

            ulong expected = 0UL;
            for (int i = 0; i < 8; ++i)
            {
                expected = (expected << 8) | fingerprint[i];
            }

            Assert.AreEqual((long)expected, key.KeyId);
        }

        [Test]
        public void UserIdSelfSignatureVerifies()
        {
            PgpPublicKey key = ReadCertificate(SequoiaCertificate);
            string userId = key.GetUserIds().Cast<string>().First();

            PgpSignature sig = key.GetSignaturesForId(userId).Cast<PgpSignature>().First();
            Assert.AreEqual(SignaturePacket.Version6, sig.Version);

            sig.InitVerify(key);
            Assert.IsTrue(sig.VerifyCertification(userId, key));
        }

        [Test]
        public void TamperedPrimaryKeyIsRejected()
        {
            // Offset 12 is inside the primary key material. Substituting a key
            // is what verification exists to catch.
            byte[] body = Dearmor(SequoiaCertificate);
            body[12] ^= 0x01;

            Assert.IsFalse(DirectKeySignatureVerifies(body));
        }

        [Test]
        public void TamperedDirectKeySignatureIsRejected()
        {
            byte[] body = Dearmor(SequoiaCertificate);

            // The Direct Key signature is the second packet; its last octet is
            // inside its Ed25519 signature material.
            int directKeyEnd = 2 + body[1] + 2 + body[2 + body[1] + 1];
            body[directKeyEnd - 1] ^= 0x01;

            Assert.IsFalse(DirectKeySignatureVerifies(body));
        }

        [Test]
        public void SaltIsTheSizeTheHashAlgorithmRequires()
        {
            // RFC 9580 5.2.3 fixes the salt size per hash algorithm. Hashing a
            // salt of any other length would hash a different byte sequence
            // than the signer did.
            PgpPublicKey key = ReadCertificate(SequoiaCertificate);
            PgpSignature directKey = GetSignatureOfType(key, PgpSignature.DirectKey);

            Assert.AreEqual(HashAlgorithmTag.Sha512, directKey.HashAlgorithm);

            // Verification reproduces the salted hash, so this passing at all
            // means the salt was read and fed in at the right size.
            directKey.InitVerify(key);
            Assert.IsTrue(directKey.VerifyCertification(key));
        }

        private static bool DirectKeySignatureVerifies(byte[] body)
        {
            try
            {
                PgpPublicKey key = ReadRing(body).GetPublicKey();
                PgpSignature directKey = GetSignatureOfType(key, PgpSignature.DirectKey);
                if (directKey == null)
                    return false;

                directKey.InitVerify(key);
                return directKey.VerifyCertification(key);
            }
            catch (Exception)
            {
                // A certificate mangled badly enough not to parse is refused
                // just as firmly as one whose signature does not verify.
                return false;
            }
        }

        private static PgpSignature GetSignatureOfType(PgpPublicKey key, int signatureType)
        {
            return key.GetSignatures().Cast<PgpSignature>()
                .FirstOrDefault(sig => sig.SignatureType == signatureType);
        }

        private static PgpPublicKey ReadCertificate(string armored)
        {
            return ReadRing(armored).GetPublicKey();
        }

        private static PgpPublicKeyRing ReadRing(string armored)
        {
            return ReadRing(Dearmor(armored));
        }

        private static PgpPublicKeyRing ReadRing(byte[] body)
        {
            return (PgpPublicKeyRing)new PgpObjectFactory(new MemoryStream(body, false)).NextPgpObject();
        }

        private static byte[] Dearmor(string armored)
        {
            using (var text = new MemoryStream(System.Text.Encoding.ASCII.GetBytes(armored), false))
            using (var armor = new ArmoredInputStream(text))
            using (var binary = new MemoryStream())
            {
                armor.CopyTo(binary);
                return binary.ToArray();
            }
        }
    }
}
